# Generated by Django 5.2.4 on 2025-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nacionality', models.CharField(blank=True, max_length=30, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
