# Generated by Django 5.2.4 on 2025-08-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editora', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('site', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subTitulo', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('idioma', models.CharField(default='Portugues')),
                ('descricao', models.TextField()),
                ('paginas', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('dimensoes', models.CharField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editora')),
            ],
        ),
    ]
